//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_of_company
    {
        public long id { get; set; }
        public long id_category { get; set; }
        public long id_company { get; set; }
    
        public virtual category category { get; set; }
        public virtual company company { get; set; }
    }
}
