//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.category_of_company = new HashSet<category_of_company>();
            this.user_of_company = new HashSet<user_of_company>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string town { get; set; }
        public string zipCode { get; set; }
        public string telephone { get; set; }
        public string mail { get; set; }
        public bool validate { get; set; }
        public int nbEmployee { get; set; }
    
        public virtual ICollection<category_of_company> category_of_company { get; set; }
        public virtual ICollection<user_of_company> user_of_company { get; set; }

        public int nb
        {
            get { return nbEmployee; }
        }
    }
}
