//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public @event()
        {
            this.user_of_event = new HashSet<user_of_event>();
        }
    
        public long id { get; set; }
        public long id_school { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string town { get; set; }
        public string zipCode { get; set; }
        public string telephone { get; set; }
        public string mail { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual school school { get; set; }
        public virtual ICollection<user_of_event> user_of_event { get; set; }
    }
}
