//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipWindowsForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModeleEntity : DbContext
    {
        public ModeleEntity()
            : base("name=ModeleEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<category_of_company> category_of_company { get; set; }
        public DbSet<company> company { get; set; }
        public DbSet<@event> @event { get; set; }
        public DbSet<journal> journal { get; set; }
        public DbSet<person> person { get; set; }
        public DbSet<school> school { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<user_of_company> user_of_company { get; set; }
        public DbSet<user_of_event> user_of_event { get; set; }
    }
}
