//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public long id { get; set; }
        public long id_person { get; set; }
        public string action { get; set; }
        public string description { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual person person { get; set; }

        public string muName
        {
            get { return person.firstName + " " + person.lastName; }
        }
    }
}
