//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.user_of_company = new HashSet<user_of_company>();
            this.user_of_event = new HashSet<user_of_event>();
        }
    
        public long id { get; set; }
        public long id_person { get; set; }
    
        public virtual person person { get; set; }
        public virtual ICollection<user_of_company> user_of_company { get; set; }
        public virtual ICollection<user_of_event> user_of_event { get; set; }
    }
}
