//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternshipWindowsForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_of_event
    {
        public long id { get; set; }
        public long id_user { get; set; }
        public long id_event { get; set; }
    
        public virtual @event @event { get; set; }
        public virtual user user { get; set; }
    }
}
